name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
    outputs:
      image_url:
        value: ${{ jobs.docker.outputs.image_url }}

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      image_url: ${{ steps.set-image.outputs.image_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.docker_token }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Set Short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Image (multi-tag)
        run: |
          docker build \
            -t ${{ inputs.image_name }}:latest \
            -t ${{ inputs.image_name }}:sha-${SHORT_SHA} .

      - name: Push Images
        run: |
          docker push ${{ inputs.image_name }}:latest
          docker push ${{ inputs.image_name }}:sha-${SHORT_SHA}

      - name: Set Output
        id: set-image
        run: echo "image_url=${{ inputs.image_name }}:latest" >> $GITHUB_OUTPUT